# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_vp_global_optspecs
	string join \n V/version h/help
end

function __fish_vp_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_vp_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_vp_using_subcommand
	set -l cmd (__fish_vp_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c vp -n "__fish_vp_needs_command" -s V -l version -d 'Print version'
complete -c vp -n "__fish_vp_needs_command" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_needs_command" -f -a "install" -d 'Install all dependencies, or add packages if package names are provided'
complete -c vp -n "__fish_vp_needs_command" -f -a "i" -d 'Install all dependencies, or add packages if package names are provided'
complete -c vp -n "__fish_vp_needs_command" -f -a "add" -d 'Add packages to dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "remove" -d 'Remove packages from dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "rm" -d 'Remove packages from dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "un" -d 'Remove packages from dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "uninstall" -d 'Remove packages from dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "update" -d 'Update packages to their latest versions'
complete -c vp -n "__fish_vp_needs_command" -f -a "up" -d 'Update packages to their latest versions'
complete -c vp -n "__fish_vp_needs_command" -f -a "dedupe" -d 'Deduplicate dependencies'
complete -c vp -n "__fish_vp_needs_command" -f -a "outdated" -d 'Check for outdated packages'
complete -c vp -n "__fish_vp_needs_command" -f -a "why" -d 'Show why a package is installed'
complete -c vp -n "__fish_vp_needs_command" -f -a "explain" -d 'Show why a package is installed'
complete -c vp -n "__fish_vp_needs_command" -f -a "info" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_needs_command" -f -a "view" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_needs_command" -f -a "show" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_needs_command" -f -a "link" -d 'Link packages for local development'
complete -c vp -n "__fish_vp_needs_command" -f -a "ln" -d 'Link packages for local development'
complete -c vp -n "__fish_vp_needs_command" -f -a "unlink" -d 'Unlink packages'
complete -c vp -n "__fish_vp_needs_command" -f -a "dlx" -d 'Execute a package binary without installing it'
complete -c vp -n "__fish_vp_needs_command" -f -a "pm" -d 'Forward a command to the package manager'
complete -c vp -n "__fish_vp_needs_command" -f -a "create" -d 'Create a new project from a template (delegates to JS)'
complete -c vp -n "__fish_vp_needs_command" -f -a "migrate" -d 'Migrate an existing project to Vite+ (delegates to JS)'
complete -c vp -n "__fish_vp_needs_command" -f -a "config" -d 'In-repo configuration (hooks, agent integration)'
complete -c vp -n "__fish_vp_needs_command" -f -a "staged" -d 'Run vite-staged on Git staged files'
complete -c vp -n "__fish_vp_needs_command" -f -a "dev" -d 'Run the development server'
complete -c vp -n "__fish_vp_needs_command" -f -a "build" -d 'Build application'
complete -c vp -n "__fish_vp_needs_command" -f -a "test" -d 'Run tests'
complete -c vp -n "__fish_vp_needs_command" -f -a "lint" -d 'Lint code'
complete -c vp -n "__fish_vp_needs_command" -f -a "fmt" -d 'Format code'
complete -c vp -n "__fish_vp_needs_command" -f -a "check" -d 'Run format, lint, and type checks'
complete -c vp -n "__fish_vp_needs_command" -f -a "pack" -d 'Build library'
complete -c vp -n "__fish_vp_needs_command" -f -a "run" -d 'Run tasks'
complete -c vp -n "__fish_vp_needs_command" -f -a "exec" -d 'Execute a command from local node_modules/.bin'
complete -c vp -n "__fish_vp_needs_command" -f -a "preview" -d 'Preview production build'
complete -c vp -n "__fish_vp_needs_command" -f -a "cache" -d 'Manage the task cache'
complete -c vp -n "__fish_vp_needs_command" -f -a "env" -d 'Manage Node.js versions'
complete -c vp -n "__fish_vp_needs_command" -f -a "upgrade" -d 'Update vp itself to the latest version'
complete -c vp -n "__fish_vp_needs_command" -f -a "implode" -d 'Remove vp and all related data'
complete -c vp -n "__fish_vp_using_subcommand install" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand install" -l node -d 'Node.js version to use for global installation (only with -g)' -r
complete -c vp -n "__fish_vp_using_subcommand install" -s P -l prod -d 'Do not install devDependencies'
complete -c vp -n "__fish_vp_using_subcommand install" -s D -l dev -d 'Only install devDependencies (install) / Save to devDependencies (add)'
complete -c vp -n "__fish_vp_using_subcommand install" -l no-optional -d 'Do not install optionalDependencies'
complete -c vp -n "__fish_vp_using_subcommand install" -l frozen-lockfile -d 'Fail if lockfile needs to be updated (CI mode)'
complete -c vp -n "__fish_vp_using_subcommand install" -l no-frozen-lockfile -d 'Allow lockfile updates (opposite of --frozen-lockfile)'
complete -c vp -n "__fish_vp_using_subcommand install" -l lockfile-only -d 'Only update lockfile, don\'t install'
complete -c vp -n "__fish_vp_using_subcommand install" -l prefer-offline -d 'Use cached packages when available'
complete -c vp -n "__fish_vp_using_subcommand install" -l offline -d 'Only use packages already in cache'
complete -c vp -n "__fish_vp_using_subcommand install" -s f -l force -d 'Force reinstall all dependencies'
complete -c vp -n "__fish_vp_using_subcommand install" -l ignore-scripts -d 'Do not run lifecycle scripts'
complete -c vp -n "__fish_vp_using_subcommand install" -l no-lockfile -d 'Don\'t read or generate lockfile'
complete -c vp -n "__fish_vp_using_subcommand install" -l fix-lockfile -d 'Fix broken lockfile entries (pnpm and yarn@2+ only)'
complete -c vp -n "__fish_vp_using_subcommand install" -l shamefully-hoist -d 'Create flat `node_modules` (pnpm only)'
complete -c vp -n "__fish_vp_using_subcommand install" -l resolution-only -d 'Re-run resolution for peer dependency analysis (pnpm only)'
complete -c vp -n "__fish_vp_using_subcommand install" -l silent -d 'Suppress output (silent mode)'
complete -c vp -n "__fish_vp_using_subcommand install" -s w -l workspace-root -d 'Install in workspace root only'
complete -c vp -n "__fish_vp_using_subcommand install" -s E -l save-exact -d 'Save exact version (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand install" -l save-peer -d 'Save to peerDependencies (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand install" -s O -l save-optional -d 'Save to optionalDependencies (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand install" -l save-catalog -d 'Save the new dependency to the default catalog (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand install" -s g -l global -d 'Install globally (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand install" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand i" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand i" -l node -d 'Node.js version to use for global installation (only with -g)' -r
complete -c vp -n "__fish_vp_using_subcommand i" -s P -l prod -d 'Do not install devDependencies'
complete -c vp -n "__fish_vp_using_subcommand i" -s D -l dev -d 'Only install devDependencies (install) / Save to devDependencies (add)'
complete -c vp -n "__fish_vp_using_subcommand i" -l no-optional -d 'Do not install optionalDependencies'
complete -c vp -n "__fish_vp_using_subcommand i" -l frozen-lockfile -d 'Fail if lockfile needs to be updated (CI mode)'
complete -c vp -n "__fish_vp_using_subcommand i" -l no-frozen-lockfile -d 'Allow lockfile updates (opposite of --frozen-lockfile)'
complete -c vp -n "__fish_vp_using_subcommand i" -l lockfile-only -d 'Only update lockfile, don\'t install'
complete -c vp -n "__fish_vp_using_subcommand i" -l prefer-offline -d 'Use cached packages when available'
complete -c vp -n "__fish_vp_using_subcommand i" -l offline -d 'Only use packages already in cache'
complete -c vp -n "__fish_vp_using_subcommand i" -s f -l force -d 'Force reinstall all dependencies'
complete -c vp -n "__fish_vp_using_subcommand i" -l ignore-scripts -d 'Do not run lifecycle scripts'
complete -c vp -n "__fish_vp_using_subcommand i" -l no-lockfile -d 'Don\'t read or generate lockfile'
complete -c vp -n "__fish_vp_using_subcommand i" -l fix-lockfile -d 'Fix broken lockfile entries (pnpm and yarn@2+ only)'
complete -c vp -n "__fish_vp_using_subcommand i" -l shamefully-hoist -d 'Create flat `node_modules` (pnpm only)'
complete -c vp -n "__fish_vp_using_subcommand i" -l resolution-only -d 'Re-run resolution for peer dependency analysis (pnpm only)'
complete -c vp -n "__fish_vp_using_subcommand i" -l silent -d 'Suppress output (silent mode)'
complete -c vp -n "__fish_vp_using_subcommand i" -s w -l workspace-root -d 'Install in workspace root only'
complete -c vp -n "__fish_vp_using_subcommand i" -s E -l save-exact -d 'Save exact version (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand i" -l save-peer -d 'Save to peerDependencies (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand i" -s O -l save-optional -d 'Save to optionalDependencies (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand i" -l save-catalog -d 'Save the new dependency to the default catalog (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand i" -s g -l global -d 'Install globally (only when adding packages)'
complete -c vp -n "__fish_vp_using_subcommand i" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand add" -l save-catalog-name -d 'Save the new dependency to the specified catalog name' -r
complete -c vp -n "__fish_vp_using_subcommand add" -l allow-build -d 'A list of package names allowed to run postinstall' -r
complete -c vp -n "__fish_vp_using_subcommand add" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand add" -l node -d 'Node.js version to use for global installation (only with -g)' -r
complete -c vp -n "__fish_vp_using_subcommand add" -s P -l save-prod -d 'Save to `dependencies` (default)'
complete -c vp -n "__fish_vp_using_subcommand add" -s D -l save-dev -d 'Save to `devDependencies`'
complete -c vp -n "__fish_vp_using_subcommand add" -l save-peer -d 'Save to `peerDependencies` and `devDependencies`'
complete -c vp -n "__fish_vp_using_subcommand add" -s O -l save-optional -d 'Save to `optionalDependencies`'
complete -c vp -n "__fish_vp_using_subcommand add" -s E -l save-exact -d 'Save exact version rather than semver range'
complete -c vp -n "__fish_vp_using_subcommand add" -l save-catalog -d 'Save the new dependency to the default catalog'
complete -c vp -n "__fish_vp_using_subcommand add" -s w -l workspace-root -d 'Add to workspace root'
complete -c vp -n "__fish_vp_using_subcommand add" -l workspace -d 'Only add if package exists in workspace (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand add" -s g -l global -d 'Install globally'
complete -c vp -n "__fish_vp_using_subcommand add" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand remove" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand remove" -s D -l save-dev -d 'Only remove from `devDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand remove" -s O -l save-optional -d 'Only remove from `optionalDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand remove" -s P -l save-prod -d 'Only remove from `dependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand remove" -s w -l workspace-root -d 'Remove from workspace root'
complete -c vp -n "__fish_vp_using_subcommand remove" -s r -l recursive -d 'Remove recursively from all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand remove" -s g -l global -d 'Remove global packages'
complete -c vp -n "__fish_vp_using_subcommand remove" -l dry-run -d 'Preview what would be removed without actually removing (only with -g)'
complete -c vp -n "__fish_vp_using_subcommand remove" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand rm" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand rm" -s D -l save-dev -d 'Only remove from `devDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand rm" -s O -l save-optional -d 'Only remove from `optionalDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand rm" -s P -l save-prod -d 'Only remove from `dependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand rm" -s w -l workspace-root -d 'Remove from workspace root'
complete -c vp -n "__fish_vp_using_subcommand rm" -s r -l recursive -d 'Remove recursively from all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand rm" -s g -l global -d 'Remove global packages'
complete -c vp -n "__fish_vp_using_subcommand rm" -l dry-run -d 'Preview what would be removed without actually removing (only with -g)'
complete -c vp -n "__fish_vp_using_subcommand rm" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand un" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand un" -s D -l save-dev -d 'Only remove from `devDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand un" -s O -l save-optional -d 'Only remove from `optionalDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand un" -s P -l save-prod -d 'Only remove from `dependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand un" -s w -l workspace-root -d 'Remove from workspace root'
complete -c vp -n "__fish_vp_using_subcommand un" -s r -l recursive -d 'Remove recursively from all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand un" -s g -l global -d 'Remove global packages'
complete -c vp -n "__fish_vp_using_subcommand un" -l dry-run -d 'Preview what would be removed without actually removing (only with -g)'
complete -c vp -n "__fish_vp_using_subcommand un" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s D -l save-dev -d 'Only remove from `devDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s O -l save-optional -d 'Only remove from `optionalDependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s P -l save-prod -d 'Only remove from `dependencies` (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s w -l workspace-root -d 'Remove from workspace root'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s r -l recursive -d 'Remove recursively from all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s g -l global -d 'Remove global packages'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -l dry-run -d 'Preview what would be removed without actually removing (only with -g)'
complete -c vp -n "__fish_vp_using_subcommand uninstall" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand update" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand update" -s L -l latest -d 'Update to latest version (ignore semver range)'
complete -c vp -n "__fish_vp_using_subcommand update" -s g -l global -d 'Update global packages'
complete -c vp -n "__fish_vp_using_subcommand update" -s r -l recursive -d 'Update recursively in all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand update" -s w -l workspace-root -d 'Include workspace root'
complete -c vp -n "__fish_vp_using_subcommand update" -s D -l dev -d 'Update only devDependencies'
complete -c vp -n "__fish_vp_using_subcommand update" -s P -l prod -d 'Update only dependencies (production)'
complete -c vp -n "__fish_vp_using_subcommand update" -s i -l interactive -d 'Interactive mode'
complete -c vp -n "__fish_vp_using_subcommand update" -l no-optional -d 'Don\'t update optionalDependencies'
complete -c vp -n "__fish_vp_using_subcommand update" -l no-save -d 'Update lockfile only, don\'t modify package.json'
complete -c vp -n "__fish_vp_using_subcommand update" -l workspace -d 'Only update if package exists in workspace (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand update" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand up" -l filter -d 'Filter packages in monorepo (can be used multiple times)' -r
complete -c vp -n "__fish_vp_using_subcommand up" -s L -l latest -d 'Update to latest version (ignore semver range)'
complete -c vp -n "__fish_vp_using_subcommand up" -s g -l global -d 'Update global packages'
complete -c vp -n "__fish_vp_using_subcommand up" -s r -l recursive -d 'Update recursively in all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand up" -s w -l workspace-root -d 'Include workspace root'
complete -c vp -n "__fish_vp_using_subcommand up" -s D -l dev -d 'Update only devDependencies'
complete -c vp -n "__fish_vp_using_subcommand up" -s P -l prod -d 'Update only dependencies (production)'
complete -c vp -n "__fish_vp_using_subcommand up" -s i -l interactive -d 'Interactive mode'
complete -c vp -n "__fish_vp_using_subcommand up" -l no-optional -d 'Don\'t update optionalDependencies'
complete -c vp -n "__fish_vp_using_subcommand up" -l no-save -d 'Update lockfile only, don\'t modify package.json'
complete -c vp -n "__fish_vp_using_subcommand up" -l workspace -d 'Only update if package exists in workspace (pnpm-specific)'
complete -c vp -n "__fish_vp_using_subcommand up" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand dedupe" -l check -d 'Check if deduplication would make changes'
complete -c vp -n "__fish_vp_using_subcommand dedupe" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand outdated" -l format -d 'Output format: table (default), list, or json' -r
complete -c vp -n "__fish_vp_using_subcommand outdated" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand outdated" -l sort-by -d 'Sort results by field' -r
complete -c vp -n "__fish_vp_using_subcommand outdated" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s r -l recursive -d 'Check recursively across all workspaces'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s w -l workspace-root -d 'Include workspace root'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s P -l prod -d 'Only production and optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s D -l dev -d 'Only dev dependencies'
complete -c vp -n "__fish_vp_using_subcommand outdated" -l no-optional -d 'Exclude optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand outdated" -l compatible -d 'Only show compatible versions'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s g -l global -d 'Check globally installed packages'
complete -c vp -n "__fish_vp_using_subcommand outdated" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand why" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand why" -l depth -d 'Limit tree depth' -r
complete -c vp -n "__fish_vp_using_subcommand why" -l find-by -d 'Use a finder function defined in .pnpmfile.cjs' -r
complete -c vp -n "__fish_vp_using_subcommand why" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand why" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand why" -l parseable -d 'Show parseable output'
complete -c vp -n "__fish_vp_using_subcommand why" -s r -l recursive -d 'Check recursively across all workspaces'
complete -c vp -n "__fish_vp_using_subcommand why" -s w -l workspace-root -d 'Check in workspace root'
complete -c vp -n "__fish_vp_using_subcommand why" -s P -l prod -d 'Only production dependencies'
complete -c vp -n "__fish_vp_using_subcommand why" -s D -l dev -d 'Only dev dependencies'
complete -c vp -n "__fish_vp_using_subcommand why" -l no-optional -d 'Exclude optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand why" -s g -l global -d 'Check globally installed packages'
complete -c vp -n "__fish_vp_using_subcommand why" -l exclude-peers -d 'Exclude peer dependencies'
complete -c vp -n "__fish_vp_using_subcommand why" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand explain" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand explain" -l depth -d 'Limit tree depth' -r
complete -c vp -n "__fish_vp_using_subcommand explain" -l find-by -d 'Use a finder function defined in .pnpmfile.cjs' -r
complete -c vp -n "__fish_vp_using_subcommand explain" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand explain" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand explain" -l parseable -d 'Show parseable output'
complete -c vp -n "__fish_vp_using_subcommand explain" -s r -l recursive -d 'Check recursively across all workspaces'
complete -c vp -n "__fish_vp_using_subcommand explain" -s w -l workspace-root -d 'Check in workspace root'
complete -c vp -n "__fish_vp_using_subcommand explain" -s P -l prod -d 'Only production dependencies'
complete -c vp -n "__fish_vp_using_subcommand explain" -s D -l dev -d 'Only dev dependencies'
complete -c vp -n "__fish_vp_using_subcommand explain" -l no-optional -d 'Exclude optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand explain" -s g -l global -d 'Check globally installed packages'
complete -c vp -n "__fish_vp_using_subcommand explain" -l exclude-peers -d 'Exclude peer dependencies'
complete -c vp -n "__fish_vp_using_subcommand explain" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand info" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand info" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand view" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand view" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand show" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand show" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand link" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand ln" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand unlink" -s r -l recursive -d 'Unlink in every workspace package'
complete -c vp -n "__fish_vp_using_subcommand unlink" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand dlx" -s p -l package -d 'Package(s) to install before running' -r
complete -c vp -n "__fish_vp_using_subcommand dlx" -s c -l shell-mode -d 'Execute within a shell environment'
complete -c vp -n "__fish_vp_using_subcommand dlx" -s s -l silent -d 'Suppress all output except the executed command\'s output'
complete -c vp -n "__fish_vp_using_subcommand dlx" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "prune" -d 'Remove unnecessary packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "pack" -d 'Create a tarball of the package'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "list" -d 'List installed packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "ls" -d 'List installed packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "view" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "info" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "show" -d 'View package information from the registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "publish" -d 'Publish package to registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "owner" -d 'Manage package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "author" -d 'Manage package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "cache" -d 'Manage package cache'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "config" -d 'Manage package manager configuration'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "c" -d 'Manage package manager configuration'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "login" -d 'Log in to a registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "adduser" -d 'Log in to a registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "logout" -d 'Log out from a registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "whoami" -d 'Show the current logged-in user'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "token" -d 'Manage authentication tokens'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "audit" -d 'Run a security audit'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "dist-tag" -d 'Manage distribution tags'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "deprecate" -d 'Deprecate a package version'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "search" -d 'Search for packages in the registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "rebuild" -d 'Rebuild native modules'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "rb" -d 'Rebuild native modules'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "fund" -d 'Show funding information for installed packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and not __fish_seen_subcommand_from prune pack list ls view info show publish owner author cache config c login adduser logout whoami token audit dist-tag deprecate search rebuild rb fund ping" -f -a "ping" -d 'Ping the registry'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from prune" -l prod -d 'Remove devDependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from prune" -l no-optional -d 'Remove optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from prune" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -l filter -d 'Filter packages to pack' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -l out -d 'Output path for the tarball' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -l pack-destination -d 'Directory where the tarball will be saved' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -l pack-gzip-level -d 'Gzip compression level (0-9)' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -s r -l recursive -d 'Pack all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from pack" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l depth -d 'Maximum depth of dependency tree' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l find-by -d 'Use a finder function' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l parseable -d 'Parseable output format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -s P -l prod -d 'Only production dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -s D -l dev -d 'Only dev dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l no-optional -d 'Exclude optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l exclude-peers -d 'Exclude peer dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -l only-projects -d 'Show only project packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -s r -l recursive -d 'List across all workspaces'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -s g -l global -d 'List global packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l depth -d 'Maximum depth of dependency tree' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l find-by -d 'Use a finder function' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l parseable -d 'Parseable output format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -s P -l prod -d 'Only production dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -s D -l dev -d 'Only dev dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l no-optional -d 'Exclude optional dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l exclude-peers -d 'Exclude peer dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -l only-projects -d 'Show only project packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -s r -l recursive -d 'List across all workspaces'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -s g -l global -d 'List global packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ls" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from view" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from view" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from info" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from show" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l tag -d 'Publish tag' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l access -d 'Access level (public/restricted)' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l otp -d 'One-time password for authentication' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l publish-branch -d 'Set the branch name to publish from' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l filter -d 'Filter packages in monorepo' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l dry-run -d 'Preview without publishing'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l no-git-checks -d 'Skip git checks'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l report-summary -d 'Save publish summary'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l force -d 'Force publish'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -s r -l recursive -d 'Publish all workspace packages'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from publish" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from owner" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from owner" -f -a "list" -d 'List package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from owner" -f -a "ls" -d 'List package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from owner" -f -a "add" -d 'Add package owner'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from owner" -f -a "rm" -d 'Remove package owner'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from author" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from author" -f -a "list" -d 'List package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from author" -f -a "ls" -d 'List package owners'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from author" -f -a "add" -d 'Add package owner'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from author" -f -a "rm" -d 'Remove package owner'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from cache" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from config" -f -a "list" -d 'List all configuration'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from config" -f -a "get" -d 'Get configuration value'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from config" -f -a "set" -d 'Set configuration value'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from config" -f -a "delete" -d 'Delete configuration key'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from c" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from c" -f -a "list" -d 'List all configuration'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from c" -f -a "get" -d 'Get configuration value'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from c" -f -a "set" -d 'Set configuration value'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from c" -f -a "delete" -d 'Delete configuration key'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from login" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from login" -l scope -d 'Scope for the login' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from adduser" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from adduser" -l scope -d 'Scope for the login' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from adduser" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from logout" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from logout" -l scope -d 'Scope for the logout' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from logout" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from whoami" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from whoami" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from token" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from token" -f -a "list" -d 'List all known tokens'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from token" -f -a "ls" -d 'List all known tokens'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from token" -f -a "create" -d 'Create a new authentication token'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from token" -f -a "revoke" -d 'Revoke an authentication token'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from audit" -l level -d 'Minimum vulnerability level to report' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from audit" -l fix -d 'Automatically fix vulnerabilities'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from audit" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from audit" -l production -d 'Only audit production dependencies'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from audit" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from dist-tag" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from dist-tag" -f -a "list" -d 'List distribution tags for a package'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from dist-tag" -f -a "ls" -d 'List distribution tags for a package'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from dist-tag" -f -a "add" -d 'Add a distribution tag'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from dist-tag" -f -a "rm" -d 'Remove a distribution tag'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from deprecate" -l otp -d 'One-time password for authentication' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from deprecate" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from deprecate" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from search" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from search" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from search" -l long -d 'Show extended information'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from rebuild" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from rb" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from fund" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from fund" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ping" -l registry -d 'Registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand pm; and __fish_seen_subcommand_from ping" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "current" -d 'Show current environment information'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "print" -d 'Print shell snippet to set environment for current session'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "default" -d 'Set or show the global default Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "on" -d 'Enable managed mode - shims always use vite-plus managed Node.js'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "off" -d 'Enable system-first mode - shims prefer system Node.js, fallback to managed'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "setup" -d 'Create or update shims in VITE_PLUS_HOME/bin'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "doctor" -d 'Run diagnostics and show environment status'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "which" -d 'Show path to the tool that would be executed'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "pin" -d 'Pin a Node.js version in the current directory (creates .node-version)'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "unpin" -d 'Remove the .node-version file from current directory (alias for `pin --unpin`)'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "list" -d 'List locally installed Node.js versions'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "ls" -d 'List locally installed Node.js versions'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "list-remote" -d 'List available Node.js versions from the registry'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "ls-remote" -d 'List available Node.js versions from the registry'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "exec" -d 'Execute a command with a specific Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "run" -d 'Execute a command with a specific Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "uninstall" -d 'Uninstall a Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "uni" -d 'Uninstall a Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "install" -d 'Install a Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "i" -d 'Install a Node.js version'
complete -c vp -n "__fish_vp_using_subcommand env; and not __fish_seen_subcommand_from current print default on off setup doctor which pin unpin list ls list-remote ls-remote exec run uninstall uni install i use" -f -a "use" -d 'Use a specific Node.js version for this shell session'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from current" -l json -d 'Output in JSON format'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from current" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from print" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from default" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from on" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from off" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from setup" -l refresh -d 'Force refresh shims even if they exist'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from setup" -l env-only -d 'Only create env files (skip shims and instructions)'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from setup" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from doctor" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from which" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from pin" -l unpin -d 'Remove the .node-version file from current directory'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from pin" -l no-install -d 'Skip pre-downloading the pinned version'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from pin" -l force -d 'Overwrite existing .node-version without confirmation'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from pin" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from unpin" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list" -l json -d 'Output as JSON'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls" -l json -d 'Output as JSON'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list-remote" -l sort -d 'Version sorting order' -r -f -a "asc\t'Sort versions in ascending order (earliest to latest)'
desc\t'Sort versions in descending order (latest to earliest)'"
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list-remote" -l lts -d 'Show only LTS versions'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list-remote" -l all -d 'Show all versions (not just recent)'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list-remote" -l json -d 'Output as JSON'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from list-remote" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls-remote" -l sort -d 'Version sorting order' -r -f -a "asc\t'Sort versions in ascending order (earliest to latest)'
desc\t'Sort versions in descending order (latest to earliest)'"
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls-remote" -l lts -d 'Show only LTS versions'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls-remote" -l all -d 'Show all versions (not just recent)'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls-remote" -l json -d 'Output as JSON'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from ls-remote" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from exec" -l node -d 'Node.js version to use (e.g., "20.18.0", "lts", "^20.0.0") If not provided and command is node/npm/npx or a global package binary, version is resolved automatically (same as shim behavior)' -r
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from exec" -l npm -d 'npm version to use (optional, defaults to bundled)' -r
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from exec" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from run" -l node -d 'Node.js version to use (e.g., "20.18.0", "lts", "^20.0.0") If not provided and command is node/npm/npx or a global package binary, version is resolved automatically (same as shim behavior)' -r
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from run" -l npm -d 'npm version to use (optional, defaults to bundled)' -r
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from uni" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from i" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from use" -l unset -d 'Remove session override (revert to file-based resolution)'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from use" -l no-install -d 'Skip auto-installation if version not present'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from use" -l silent-if-unchanged -d 'Suppress output if version is already active'
complete -c vp -n "__fish_vp_using_subcommand env; and __fish_seen_subcommand_from use" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l tag -d 'npm dist-tag to install (default: "latest", also: "alpha")' -r
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l registry -d 'Custom npm registry URL' -r
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l check -d 'Check for updates without installing'
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l rollback -d 'Revert to the previously active version'
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l force -d 'Force reinstall even if already on the target version'
complete -c vp -n "__fish_vp_using_subcommand upgrade" -l silent -d 'Suppress output'
complete -c vp -n "__fish_vp_using_subcommand upgrade" -s h -l help -d 'Print help'
complete -c vp -n "__fish_vp_using_subcommand implode" -s y -l yes -d 'Skip confirmation prompt'
complete -c vp -n "__fish_vp_using_subcommand implode" -s h -l help -d 'Print help'
